#collect_par collected_parameters  # set this parameter if user wants to collect parameters

#reaction_name     proton_10MeV
#reaction_name     241Am_a1
#reaction_name     test
#reaction_name     34Ar
reaction_name     alpha_test

LKG4Manager/VisMode               true
#LKG4Manager/G4OutputFile          data/cssu_{reaction_name}.root
LKG4Manager/G4OutputFile          data/cssu_{reaction_name}.root
LKG4Manager/SetAutoUpdateCopyNo   true # If true, manager will automatically assign unique CopyNo of sensitive physical volumes.
LKG4Manager/SuppressG4InitMessage true
LKG4Manager/DetectorCosntruction  CSSUDetectorConstruction
LKG4Manager/WriteTextFile         true

#CSSUDetectorConstruction/WorldSize       200., 200., 500.  # mm
#CSSUDetectorConstruction/GasMaterial     He, CO2
#CSSUDetectorConstruction/GasFraction     0.97, 0.03
#CSSUDetectorConstruction/GasMaterial     CF4 # gas material name. (vacuum, CF4 ,He ,iC4H10 ,CH4 ,P80 ,CO2 ,H2 ,D2 ,MixTwinMusic ,CH4_60_He_40)
CSSUDetectorConstruction/GasMaterial     vacuum # gas material name. (vacuum, CF4 ,He ,iC4H10 ,CH4 ,P80 ,CO2 ,H2 ,D2 ,MixTwinMusic ,CH4_60_He_40)
CSSUDetectorConstruction/GasFraction     1
CSSUDetectorConstruction/GasPressure     40 torr # bar or torr
CSSUDetectorConstruction/GasTemperature  295  # kelvin
CSSUDetectorConstruction/GasVolumeSize   200., 200., 400.  # mm
CSSUDetectorConstruction/SensitiveRanges 50, 150, 250, 350           # mm, int, range of sensitive volume. ex) 0, 20, 40, 60
CSSUDetectorConstruction/StepLimitInGas  10 # mm
CSSUDetectorConstruction/SiZPosition     390
#CSSUDetectorConstruction/SiZPosition     10

NPTool/Reaction/File   nptool_{reaction_name}.reaction

NPTool/Reaction/Type                    Isotropic
NPTool/Reaction/Isotropic/Multiplicity  1
NPTool/Reaction/Isotropic/SigmaX        0. mm
NPTool/Reaction/Isotropic/SigmaY        0. mm
NPTool/Reaction/Isotropic/SigmaZ        0. mm
#NPTool/Reaction/Isotropic/SourceProfile 
#NPTool/Reaction/Isotropic/Direction     0., 0., 1.
#NPTool/Reaction/Isotropic/EnergyDistributionHist  
NPTool/Reaction/Isotropic/Particle      4He
#NPTool/Reaction/Isotropic/Particle      1H
NPTool/Reaction/Isotropic/EnergyHigh    5.486 MeV
NPTool/Reaction/Isotropic/EnergyLow     5.486 MeV
NPTool/Reaction/Isotropic/EnergyDistribution      flat
NPTool/Reaction/Isotropic/ExcitationEnergy        0. MeV
NPTool/Reaction/Isotropic/x0            0. mm
NPTool/Reaction/Isotropic/y0            0. mm
NPTool/Reaction/Isotropic/z0            -250. mm
NPTool/Reaction/Isotropic/HalfOpenAngleMin        0. deg
NPTool/Reaction/Isotropic/HalfOpenAngleMax        0. deg

G4/tracking/verbose 1
LKG4Manager/G4CommandFile         geant4_vis.mac
G4/run/beamOn 1
